### ISSUE TITLE
On/Off feature for admin

### ISSUE THREAD

**Issue by rapidfsub** [ash-project/ash_archival#3]
**Is your feature request related to a problem? Please describe.**
After deleting the resource, I still need to see the resource in admin app.

**Describe the solution you'd like**
On/Off feature for admin.
In admin app, I want to turn off the `archived_at != nil` and show all resource, even if deleted.

**Describe alternatives you've considered**
Is this out of ash_archival's context?

**Comment by rapidfsub** [comment]
@zachdaniel 
Could you give me a short comment for this?
I am wondering how do you think about this.
1. The on/off feature could be implemented in future
2. You should implement additional status between normal and archived (i.e. deleting, delete_in_progress, ...)

**Comment by zachdaniel** [comment]
The best way to accomplish the ability to view archived documents would be to make it possible to bypass ash_archival's filter for specific actions. First, we need to add an option to disable the base filter on an action by action basis. PRs welcome on both fronts :)
