### ISSUE TITLE
Allow configuring atomic upgrade behavior

### ISSUE THREAD

**Issue by emtudo** [ash-project/ash_archival#30]
**Describe the bug**
I tried everything I understood in the documentation, but I was unable to unarchive the document.
Module: https://gist.github.com/emtudo/e8040203e1070e92476dbd899c40a88d
Test: https://gist.github.com/emtudo/75c75c6abdcb1601f326b542949694fd

**To Reproduce**
Added the action:

```

    update :unarchive do
      accept [:name, :domain]
      change set_attribute(:archived_at, nil)
    end
    
    ```
    and test:
    
    ```
    test "unarchives an organization" do
      organization = Organization
        |> Ash.Changeset.for_create(:create, @valid_attrs)
        |> Ash.create!()

      organization
        |> Ash.Changeset.for_destroy(:destroy)
        |> Ash.destroy!()

      archived_organization = Organization
        |> Ash.Query.for_read(:by_id, %{id: organization.id})
        |> Ash.read_one!()

      IO.inspect(archived_organization, label: "organization xx")

      unarchived_organization =  archived_organization
        |> Ash.Changeset.for_update(:unarchive, @update_attrs)
        # |> Ash.update!()

      IO.inspect(unarchived_organization, label: "unarchived_organization")
      # assert unarchived_organization.id == organization.id

      fetched_organization = Organization
        |> Ash.Query.for_read(:archived_by_id, %{id: organization.id})
        |> Ash.read_one!()
      IO.inspect(fetched_organization, label: "fetched XX")
    end
```
and fetched_organization it is returns nil, but it should returns a data

**Expected behavior**

** Runtime
 - Elixir 1.16.2
 - Erlang 26
 - OS Linux Ubuntu 22.04
 - Ash 3.0
 - ash_archival 1.0

**Additional context**

**Comment by emtudo** [comment]
No, I commented for a test and forgot to uncomment before posting here.

**Comment by emtudo** [comment]
Error with uncomment:
![image](https://github.com/ash-project/ash_archival/assets/191396/4bcec81b-8a31-4bc7-8142-3211415cf526)

**Comment by zachdaniel** [comment]
Ah, interesting... 🤔try adding the option `atomic_upgrade?: false` to the call to create. If that works then I'll know what the issue is :)

**Comment by emtudo** [comment]
It's not clear to me where I should put it, I'm studying the framework, I'm in the first steps.

I put the project on github: https://github.com/emtudo/ash-archived

**Comment by zachdaniel** [comment]
I won't be around for a day or two to investigate aside from on my phone. Try `Ash.update(..., atomic_upgrade?: false)`

**Comment by emtudo** [comment]
|> Ash.update!(atomic_upgrade?: false)
 
 
![image](https://github.com/ash-project/ash_archival/assets/191396/d8d8bd36-e6a7-4ca4-ad35-a5c8b69511ec)

Don't work!

**Comment by zachdaniel** [comment]
One more thing, add `require_atomic? false` to the update action

**Comment by emtudo** [comment]
it's ok!

thanks!

**Comment by zachdaniel** [comment]
I'm going to leave this open actually because it's representative of a missing option, which is the ability to either 1. Turn off `atomic_upgrade?` for the action or 2. Configure an `atomic_upgrade_read_action`

**Comment by emtudo** [comment]
Very good!

**Comment by emtudo** [comment]
For me resolved with:

```elixir
    update :unarchive do
      change set_attribute(:archived_at, nil)
      require_atomic? false
    end
```

**Comment by emtudo** [comment]
@zachdaniel In the documentation it says to use update set_attribute, but for me it gives an error what works for me is "change" I don't know if in previous versions it was update, just to be aware.

**Comment by zachdaniel** [comment]
Yeah that is a typo. I will fix unless you want to do a PR?

**Comment by emtudo** [comment]
it's ok! I will!
