### ISSUE TITLE
Getting "Attempted to update stale record" when unarchiving.

### ISSUE THREAD

**Issue by alykhanjetha** [ash-project/ash_archival#59]
Coupling an update action with `atomic_upgrade_with` pointing at a read action that is ignored with `exclude_read_actions` still applies the filter and therefore doesn’t apply the update, ultimately resulting in the update action not succeeding and getting a StaleRecordError

** Runtime
 - Elixir version: 1.17.2
 - Erlang version
 - OS: macOS
 - Ash version: main branch
 - any related extension versions: ash archival, main branch

**Additional context**
Using `cascade_update` when unarchiving.

**Comment by zachdaniel** [comment]
I believe this is fixed in latest `main` of `ash`. Please reopen if not :)
